on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
      - run: uv sync
      - run: uv run mkdocs build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: yukihiko-shinoda/hello-world-github-pages-mkdocs
          publish_branch: main
          publish_dir: ./site
